import { IsString, IsNumber, IsOptional, IsArray } from 'class-validator';

/**
 * Product class representing a product entity.
 */
export class Product {
  /**
   * Unique identifier for the product. Optional as it might be generated by the system.
   */
  @IsNumber() @IsOptional() readonly id: number;

  /**
   * Title of the product.
   */
  @IsString() readonly title: string;

  /**
   * Numeric description of the product. Consider using a string or more descriptive type.
   */
  @IsNumber() readonly description: number;

  /**
   * Price of the product represented as a string.
   */
  @IsString() readonly price: string;

  /**
   * Discount percentage applied to the product as a string.
   */
  @IsString() readonly discountPercentage: string;

  /**
   * Rating of the product as a string.
   */
  @IsString() readonly rating: string;

  /**
   * Stock availability of the product as a string.
   */
  @IsString() readonly stock: string;

  /**
   * Brand of the product.
   */
  @IsString() readonly brand: string;

  /**
   * Category to which the product belongs.
   */
  @IsString() readonly category: string;

  /**
   * URL representing the thumbnail image of the product.
   */
  @IsString() readonly thumbnail: string;

  /**
   * Array of URLs representing additional images of the product.
   */
  @IsArray() @IsString({ each: true }) readonly images: string[];
}